# -*- coding: utf-8 -*-
"""Bản sao của Chào mừng bạn đến với Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kixTW7ukalOUVjdL6pBcFNrImePcPF08

#Dữ liệu học Sâu
"""

# Import thư viện
import pandas as pd

# Upload file CSV lên Colab trước
from google.colab import files
uploaded = files.upload()

# Đọc file CSV
df = pd.read_csv('dulieuxettuyendaihoc.csv')

# Hiển thị 5 dòng đầu
print(df.head())

sapxep_DH1 = df.sort_values(by='DH1', ascending=True)

print(sapxep_DH1[['STT', 'DH1']])

sapxep_DH2_GT = df.sort_values(by=['GT', 'DH2'], ascending=True)

print(sapxep_DH2_GT[['STT', 'GT', 'DH2']])

# Hàm tính Q1, Q2, Q3
Q1 = lambda x: x.quantile(0.25)
Q2 = lambda x: x.quantile(0.50)
Q3 = lambda x: x.quantile(0.75)

pivot1 = pd.pivot_table(
    df,
    values='DH1',
    index='KT',
    aggfunc=[
        'count',
        'sum',
        'mean',
        'median',
        'min',
        'max',
        'std',
        Q1,
        Q2,
        Q3
    ]
)

print(pivot1)

pivot2 = pd.pivot_table(
    df,
    values='DH1',
    index=['KT', 'KV'],
    aggfunc=[
        'count',
        'sum',
        'mean',
        'median',
        'min',
        'max',
        'std',
        Q1,
        Q2,
        Q3
    ]
)

print(pivot2)

pivot3 = pd.pivot_table(
    df,
    values='DH1',
    index=['KT', 'KV', 'DT'],
    aggfunc=[
        'count',
        'sum',
        'mean',
        'median',
        'min',
        'max',
        'std',
        Q1,
        Q2,
        Q3
    ]
)

print(pivot3)

# =========================
# LAB 2 - PHẦN 2
# TRÌNH BÀY DỮ LIỆU
# =========================

# Import thư viện
import pandas as pd
import matplotlib.pyplot as plt

# Hiển thị đầy đủ bảng
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)

# Upload file CSV
from google.colab import files
uploaded = files.upload()

# Đọc file CSV
df = pd.read_csv('dulieuxettuyendaihoc (2).csv')

# =========================
# CÂU 1: Biến GT
# =========================

print("===== CÂU 1: GT =====")

# Bảng tần số
tan_so_GT = df['GT'].value_counts()
print("\nBảng tần số:")
print(tan_so_GT)

# Bảng tần suất
tan_suat_GT = df['GT'].value_counts(normalize=True) * 100
print("\nBảng tần suất (%):")
print(tan_suat_GT)

# Biểu đồ cột
plt.figure(figsize=(6,5))
tan_so_GT.plot(kind='bar')
plt.title('Biểu đồ tần số GT')
plt.xlabel('Giới tính')
plt.ylabel('Tần số')
plt.show()

# Biểu đồ tròn
plt.figure(figsize=(6,6))
tan_suat_GT.plot(kind='pie', autopct='%1.1f%%')
plt.title('Biểu đồ tần suất GT')
plt.ylabel('')
plt.show()


# =========================
# CÂU 2: US_TBM1, US_TBM2, US_TBM3
# =========================

print("\n===== CÂU 2 =====")

# Kiểm tra nếu chưa có cột thì tạo
if 'US_TBM1' not in df.columns:
    df['US_TBM1'] = (df['T1'] + df['L1'] + df['H1']) / 3

if 'US_TBM2' not in df.columns:
    df['US_TBM2'] = (df['T2'] + df['L2'] + df['H2']) / 3

if 'US_TBM3' not in df.columns:
    df['US_TBM3'] = (df['T3'] + df['L3'] + df['H3']) / 3

# Thống kê
print(df[['US_TBM1', 'US_TBM2', 'US_TBM3']].describe())

# Vẽ histogram
df['US_TBM1'].plot(kind='hist', bins=10)
plt.title('Histogram US_TBM1')
plt.show()

df['US_TBM2'].plot(kind='hist', bins=10)
plt.title('Histogram US_TBM2')
plt.show()

df['US_TBM3'].plot(kind='hist', bins=10)
plt.title('Histogram US_TBM3')
plt.show()


# =========================
# CÂU 3: DT với học sinh nam
# =========================

print("\n===== CÂU 3 =====")

nam = df[df['GT'] == 'M']

tan_so_DT = nam['DT'].value_counts()

print("\nTần số DT của học sinh nam:")
print(tan_so_DT)

# Biểu đồ cột
plt.figure(figsize=(8,5))
tan_so_DT.plot(kind='bar')
plt.title('DT của học sinh nam')
plt.xlabel('DT')
plt.ylabel('Tần số')
plt.show()


# =========================
# CÂU 4
# KV với học sinh nam, dân tộc Kinh
# DH1 >= 5, DH2 >= 4, DH3 >= 4
# =========================

print("\n===== CÂU 4 =====")

loc_du_lieu = df[
    (df['GT'] == 'M') &
    ((df['DT'].isnull()) | (df['DT'] == 'Kinh')) &
    (df['DH1'] >= 5.0) &
    (df['DH2'] >= 4.0) &
    (df['DH3'] >= 4.0)
]

tan_so_KV = loc_du_lieu['KV'].value_counts()

print("\nTần số KV:")
print(tan_so_KV)

# Biểu đồ cột
plt.figure(figsize=(6,5))
tan_so_KV.plot(kind='bar')
plt.title('KV của học sinh nam dân tộc Kinh')
plt.xlabel('KV')
plt.ylabel('Tần số')
plt.show()


# =========================
# CÂU 5
# DH1, DH2, DH3 >= 5 thuộc KV 2NT
# =========================

print("\n===== CÂU 5 =====")

kv_2nt = df[
    (df['KV'] == '2NT') &
    (df['DH1'] >= 5.0) &
    (df['DH2'] >= 5.0) &
    (df['DH3'] >= 5.0)
]

print(kv_2nt[['STT', 'DH1', 'DH2', 'DH3', 'KV']])

# Biểu đồ điểm
plt.figure(figsize=(8,5))

plt.plot(kv_2nt['DH1'].values, label='DH1')
plt.plot(kv_2nt['DH2'].values, label='DH2')
plt.plot(kv_2nt['DH3'].values, label='DH3')

plt.title('DH1, DH2, DH3 của KV 2NT')
plt.xlabel('Học sinh')
plt.ylabel('Điểm')
plt.legend()

plt.show()

# ==============================
# LAB 2 - PHẦN 3
# TRỰC QUAN HÓA DỮ LIỆU
# ==============================

# Import thư viện
import pandas as pd
import matplotlib.pyplot as plt

# Hiển thị đầy đủ bảng
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)

# Upload file CSV
from google.colab import files
uploaded = files.upload()

# Đọc file
df = pd.read_csv('dulieuxettuyendaihoc (2).csv')

# ==========================================
# TẠO CÁC CỘT XL1, XL2, XL3
# ==========================================

def xeploai(diem):
    if diem < 5:
        return 'Y'
    elif diem < 6.5:
        return 'TB'
    elif diem < 8:
        return 'K'
    elif diem < 9:
        return 'G'
    else:
        return 'XS'

df['XL1'] = df['DH1'].apply(xeploai)
df['XL2'] = df['DH2'].apply(xeploai)
df['XL3'] = df['DH3'].apply(xeploai)

# ==========================================
# TẠO CỘT KQXT (Đậu / Rớt)
# ==========================================

def ketqua(row):
    if row['DH1'] >= 5 and row['DH2'] >= 5 and row['DH3'] >= 5:
        return 'Đậu'
    else:
        return 'Rớt'

df['KQXT'] = df.apply(ketqua, axis=1)

# ==========================================
# CÂU 1
# Học sinh nữ trên nhóm XL1 XL2 XL3
# ==========================================

print("===== CÂU 1 =====")

nu = df[df['GT'] == 'F']

bang_xl = pd.crosstab(
    index=['XL1', 'XL2', 'XL3'],
    columns='count'
)

# Tạo dữ liệu
xl1 = nu['XL1'].value_counts()
xl2 = nu['XL2'].value_counts()
xl3 = nu['XL3'].value_counts()

data = pd.DataFrame({
    'XL1': xl1,
    'XL2': xl2,
    'XL3': xl3
}).fillna(0)

data = data.reindex(['Y', 'TB', 'K', 'G', 'XS'])

# Vẽ biểu đồ
data.T.plot(kind='bar', stacked=False, figsize=(10,6))

plt.title('Học sinh nữ theo XL1 XL2 XL3')
plt.xlabel('Nhóm xếp loại')
plt.ylabel('Số lượng học sinh')

plt.show()


# ==========================================
# CÂU 2
# KQXT trên nhóm khối A A1 B thuộc KV 1,2
# ==========================================

print("===== CÂU 2 =====")

loc = df[
    (df['KT'].isin(['A', 'A1', 'B'])) &
    (df['KV'].isin(['1', '2']))
]

bang2 = pd.crosstab(loc['KT'], loc['KQXT'])

print(bang2)

bang2.plot(kind='bar', figsize=(8,5))

plt.title('KQXT theo khối thi')
plt.xlabel('Khối thi')
plt.ylabel('Số lượng')

plt.show()


# ==========================================
# CÂU 3
# Số lượng thí sinh từng KV theo khối thi
# ==========================================

print("===== CÂU 3 =====")

bang3 = pd.crosstab(df['KT'], df['KV'])

print(bang3)

bang3.plot(kind='bar', figsize=(10,6))

plt.title('Số lượng thí sinh theo KV và KT')
plt.xlabel('Khối thi')
plt.ylabel('Số lượng')

plt.show()


# ==========================================
# CÂU 4
# Đậu rớt theo nhóm khối thi
# ==========================================

print("===== CÂU 4 =====")

bang4 = pd.crosstab(df['KT'], df['KQXT'])

print(bang4)

bang4.plot(kind='bar', figsize=(8,5))

plt.title('Đậu rớt theo khối thi')
plt.xlabel('Khối thi')
plt.ylabel('Số lượng')

plt.show()


# ==========================================
# CÂU 5
# Đậu rớt theo khu vực
# ==========================================

print("===== CÂU 5 =====")

bang5 = pd.crosstab(df['KV'], df['KQXT'])

print(bang5)

bang5.plot(kind='bar', figsize=(8,5))

plt.title('Đậu rớt theo khu vực')
plt.xlabel('Khu vực')
plt.ylabel('Số lượng')

plt.show()


# ==========================================
# CÂU 6
# Đậu rớt theo dân tộc
# ==========================================

print("===== CÂU 6 =====")

# Điền NaN thành Kinh
df['DT'] = df['DT'].fillna('Kinh')

bang6 = pd.crosstab(df['DT'], df['KQXT'])

print(bang6)

bang6.plot(kind='bar', figsize=(10,6))

plt.title('Đậu rớt theo dân tộc')
plt.xlabel('Dân tộc')
plt.ylabel('Số lượng')

plt.show()


# ==========================================
# CÂU 7
# Đậu rớt theo giới tính
# ==========================================

print("===== CÂU 7 =====")

bang7 = pd.crosstab(df['GT'], df['KQXT'])

print(bang7)

bang7.plot(kind='bar', figsize=(6,5))

plt.title('Đậu rớt theo giới tính')
plt.xlabel('Giới tính')
plt.ylabel('Số lượng')

plt.show()

# =====================================================================
# LAB 2 - PHẦN 4: TRỰC QUAN HÓA DỮ LIỆU NÂNG CAO (CHUẨN KẾT QUẢ SPSS)
# =====================================================================

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Thiết lập hiển thị dữ liệu đầy đủ trên Console
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)

# ---------------------------------------------------------------------
# ĐỌC DỮ LIỆU THỰC TẾ
# Bạn chỉ cần mở dòng code bên dưới ra nếu chạy trực tiếp bằng file CSV của bạn:
# df = pd.read_csv('dulieuxettuyendaihoc (2).csv')
# ---------------------------------------------------------------------

# Giả lập tập dữ liệu T1 để code chạy được độc lập (Bỏ qua nếu bạn đã load file CSV ở trên)
import numpy as np
np.random.seed(42)
t1_sample = np.round(np.random.uniform(2.4, 9.3, 100), 1)
df = pd.DataFrame({'T1': t1_sample})


# =====================================================================
# CÂU 1: BIỂU ĐỒ ĐƯỜNG SIMPLE CHO BIẾN T1 (TÍNH THEO TẦN SUẤT - COUNT)
# =====================================================================
print("\n===== CÂU 1 =====")

# Thống kê tần suất xuất hiện của từng mức điểm T1 và sắp xếp tăng dần
df_counts = df['T1'].value_counts().reset_index()
df_counts.columns = ['T1', 'Count']
df_counts = df_counts.sort_values(by='T1').reset_index(drop=True)

plt.figure(figsize=(11, 5))

# Vẽ đường Simple Line với các mức điểm phân bổ đều nhau trên trục hoành
plt.plot(df_counts['T1'].astype(str), df_counts['Count'], color='black', linewidth=1)

plt.xlabel('T1', fontsize=10)
plt.ylabel('Count', fontsize=10)
plt.xticks(rotation=90, fontsize=8)
plt.ylim(0, df_counts['Count'].max() + 1)
plt.tight_layout()
plt.show()


# =====================================================================
# CÂU 2: TẠO BIẾN PHÂN LOẠI (phanlopt1) CHO MÔN TOÁN (T1)
# =====================================================================
print("\n===== CÂU 2 =====")

def phanloai(diem):
    if diem < 5:
        return 'k'    # Kém (Ký hiệu "k")
    elif diem < 7:
        return 'tb'   # Trung bình (Ký hiệu "tb")
    elif diem < 8:
        return 'kh'   # Khá (Ký hiệu "kh" để phân biệt rõ với "k" kém khi xử lý)
    else:
        return 'g'    # Giỏi (Ký hiệu "g")

# Tạo cột phanlopt1 theo đúng yêu cầu đề bài
df['phanlopt1'] = df['T1'].apply(phanloai)

# Hiển thị vài dòng đầu để kiểm tra kết quả
print(df[['T1', 'phanlopt1']].head(10))


# =====================================================================
# CÂU 3: LẬP BẢNG TẦN SỐ CHO BIẾN phanlopt1
# =====================================================================
print("\n===== CÂU 3 =====")

tan_so = df['phanlopt1'].value_counts()
print("Bảng tần số phân loại học lực T1:")
print(tan_so)


# =====================================================================
# CÂU 4: VẼ BIỂU ĐỒ ĐƯỜNG MULTIPLE LINE CHO T1 PHÂN LOẠI BỞI phanlopt1
# =====================================================================
print("\n===== CÂU 4 =====")

# Thống kê số lượng học sinh cho từng mức điểm thuộc từng nhóm học lực
df_multi = df.groupby(['T1', 'phanlopt1']).size().reset_index(name='Count')

# Thu thập toàn bộ các nhãn điểm duy nhất trên trục hoành phân loại để giữ khoảng cách đều
all_t1_str = sorted(df['T1'].unique().astype(str))

plt.figure(figsize=(11, 5))

# Bảng mã màu sắc và nhãn hiển thị mô phỏng theo mẫu đồ thị của SPSS
colors = {'g': '#4f81bd', 'kh': '#c0504d', 'k': '#9bbb59', 'tb': '#8064a2'}
labels = {'g': 'Gioi', 'kh': 'Kha', 'k': 'Kem', 'tb': 'Trungbinh'}

# Duyệt và vẽ từng nhóm độc lập để các đường nối liền mạch không bị ép kéo về đáy 0 lộn xộn
for group in ['g', 'k', 'kh', 'tb']:
    df_sub = df_multi[df_multi['phanlopt1'] == group].copy()

    if not df_sub.empty:
        df_sub = df_sub.sort_values(by='T1')
        plt.plot(df_sub['T1'].astype(str), df_sub['Count'],
                 label=labels[group], color=colors[group], linewidth=1.2)

plt.xlabel('T1', fontsize=10)
plt.ylabel('Count', fontsize=10)
plt.xticks(ticks=all_t1_str, labels=all_t1_str, rotation=90, fontsize=8)
plt.ylim(0, df_multi['Count'].max() + 1)

# Định vị vị trí bảng chú thích (Legend) nằm ngoài đồ thị bên phải giống SPSS
plt.legend(title='Phanlopt1', bbox_to_anchor=(1.01, 1), loc='upper left')
plt.tight_layout()
plt.show()


# =====================================================================
# CÂU 5: VẼ BIỂU ĐỒ DROP-LINE CHO T1 PHÂN LOẠI BỞI phanlopt1
# =====================================================================
print("\n===== CÂU 5 =====")

# Thống kê và sắp xếp dữ liệu gốc theo trật tự tăng dần của điểm số
df_drop = df.groupby(['T1', 'phanlopt1']).size().reset_index(name='Count')
df_drop = df_drop.sort_values(by='T1').reset_index(drop=True)
df_drop['T1_str'] = df_drop['T1'].astype(str)

plt.figure(figsize=(11, 5))

# 1. Khởi tạo các đường kẻ dọc (Drop-lines) hạ vuông góc từ vị trí điểm xuống trục đáy y=0
for idx, row in df_drop.iterrows():
    plt.vlines(x=row['T1_str'], ymin=0, ymax=row['Count'], colors='black', linewidth=1)

# 2. Đè các điểm Marker tròn có viền đen sắc nét lên đỉnh đầu của các đường kẻ dọc
sns.scatterplot(
    data=df_drop,
    x='T1_str',
    y='Count',
    hue='phanlopt1',
    hue_order=['g', 'k', 'kh', 'tb'],
    palette=colors,
    s=45,
    edgecolor='black',
    linewidth=0.8,
    zorder=3
)

# Định hình và đồng bộ hóa lại tên nhãn trong khung hiển thị chú thích nhóm
handles, labels_dict = plt.gca().get_legend_handles_labels()
new_labels = [labels.get(l, l) for l in labels_dict]

plt.xlabel('T1', fontsize=10)
plt.ylabel('Count', fontsize=10)
plt.xticks(rotation=90, fontsize=8)
plt.ylim(0, df_drop['Count'].max() + 1)
plt.legend(handles, new_labels, title='Phanlopt1', bbox_to_anchor=(1.01, 1), loc='upper left')
plt.tight_layout()
plt.show()

# =====================================================================
# LAB 2 - PHẦN 5: MÔ TẢ DỮ LIỆU VÀ KHẢO SÁT DẠNG PHÂN PHỐI
# =====================================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats

# Cấu hình hiển thị đầy đủ thông tin trên Console
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)

# ---------------------------------------------------------------------
# ĐỌC DỮ LIỆU THỰC TẾ (Bỏ chú thích dòng dưới nếu chạy file thực tế của bạn)
# df = pd.read_csv('dulieuxettuyendaihoc (2).csv')
# ---------------------------------------------------------------------

# Giả lập tập dữ liệu mẫu phục vụ chạy thử độc lập (Xóa đi nếu đã load file CSV)
np.random.seed(42)
n_samples = 100
t1_mock = np.round(np.random.normal(loc=5.5, scale=1.5, size=n_samples), 1)
t1_mock = np.clip(t1_mock, 0, 10)  # Giới hạn điểm từ 0 đến 10
dh1_mock = np.round(t1_mock * 0.6 + np.random.normal(loc=1.5, scale=0.8, size=n_samples), 1)
dh2_mock = np.round(t1_mock * 0.5 + np.random.normal(loc=2.0, scale=1.0, size=n_samples), 1)
dh3_mock = np.round(t1_mock * 0.55 + np.random.normal(loc=1.8, scale=0.9, size=n_samples), 1)

df = pd.DataFrame({'T1': t1_mock, 'DH1': dh1_mock, 'DH2': dh2_mock, 'DH3': dh3_mock})
def phanloai(diem):
    if diem < 5: return 'k'
    elif diem < 7: return 'tb'
    elif diem < 8: return 'kh'
    else: return 'g'
df['phanlopt1'] = df['T1'].apply(phanloai)


# =====================================================================
# CÂU 1: MÔ TẢ VÀ KHẢO SÁT PHÂN PHỐI CHO BIẾN T1
# =====================================================================
print("\n===== CÂU 1 =====")

# a. Mô tả độ tập trung, phân tán và các đặc trưng (lệch, nhọn)
mean_t1 = df['T1'].mean()
median_t1 = df['T1'].median()
mode_t1 = df['T1'].mode()[0]
var_t1 = df['T1'].var()
std_t1 = df['T1'].std()
skew_t1 = df['T1'].skew()
kurt_t1 = df['T1'].kurt()

print(f"--- Đặc trưng hình dáng & tập trung biến T1 ---")
print(f"Trung bình (Mean): {mean_t1:.4f}")
print(f"Trung vị (Median): {median_t1:.4f}")
print(f"Yếu vị (Mode): {mode_t1:.4f}")
print(f"Phương sai (Variance): {var_t1:.4f}")
print(f"Độ lệch chuẩn (Std Dev): {std_t1:.4f}")
print(f"Độ lệch (Skewness): {skew_t1:.4f} -> (Nếu gần 0: đối xứng, >0: lệch phải, <0: lệch trái)")
print(f"Độ nhọn (Kurtosis): {kurt_t1:.4f} -> (Nếu gần 0: phân phối chuẩn, >0: nhọn hơn, <0: dẹt hơn)")

# b. Vẽ biểu đồ Box-Plot và xác định 10 đại lượng
plt.figure(figsize=(6, 5))
sns.boxplot(y=df['T1'], color='#9bbb59')
plt.title('Biểu đồ Box-Plot của T1')
plt.ylabel('Điểm T1')
plt.show()

q1 = df['T1'].quantile(0.25)
q3 = df['T1'].quantile(0.75)
iqr = q3 - q1
min_val = df['T1'].min()
max_val = df['T1'].max()

print(f"\n--- 10 Đại lượng trong biểu đồ Box-Plot & dữ liệu ---")
print(f"1. Giá trị nhỏ nhất (Min): {min_val}")
print(f"2. Điểm phần vị thứ 25 (Q1): {q1}")
print(f"3. Điểm phần vị thứ 50 / Trung vị (Q2/Median): {median_t1}")
print(f"4. Điểm phần vị thứ 75 (Q3): {q3}")
print(f"5. Giá trị lớn nhất (Max): {max_val}")
print(f"6. Khoảng tứ phân vị (IQR): {iqr:.4f}")
print(f"7. Hàng rào dưới (Lower Fence): {q1 - 1.5*iqr:.4f}")
print(f"8. Hàng rào trên (Upper Fence): {q3 + 1.5*iqr:.4f}")
print(f"9. Số lượng mẫu (Count): {df['T1'].count()}")
print(f"10. Số lượng giá trị ngoại lai (Outliers): {df[(df['T1'] < (q1 - 1.5*iqr)) | (df['T1'] > (q3 + 1.5*iqr))]['T1'].count()}")

# c. Vẽ biểu đồ Histogram biểu thị hình dáng phân phối
plt.figure(figsize=(8, 5))
sns.histplot(df['T1'], kde=True, color='#4f81bd', bins=10)
plt.title('Biểu đồ Histogram với đường cong mật độ của T1')
plt.xlabel('Điểm T1')
plt.ylabel('Tần suất')
plt.show()

# d. Kiểm chứng phân phối chuẩn bằng QQ-Plot
plt.figure(figsize=(6, 5))
stats.probplot(df['T1'], plot=plt)
plt.title('Biểu đồ QQ-Plot kiểm chứng phân phối chuẩn của T1')
plt.show()


# =====================================================================
# CÂU 2: MÔ TẢ VÀ KHẢO SÁT PHÂN PHỐI T1 THEO TỪNG NHÓM PHÂN LỚP (phanlopt1)
# =====================================================================
print("\n===== CÂU 2 =====")

# Thống kê chi tiết T1 theo từng nhóm phân lớp
danh_gia_nhom = df.groupby('phanlopt1')['T1'].describe()
print("Thống kê mô tả T1 theo từng nhóm học lực:")
print(danh_gia_nhom)

# Trực quan hóa Box-plot theo phân nhóm
plt.figure(figsize=(8, 5))
sns.boxplot(x='phanlopt1', y='T1', data=df, palette='Set2', order=['k', 'tb', 'kh', 'g'])
plt.title('Biểu đồ Box-plot của T1 theo từng nhóm phân lớp')
plt.show()

# Trực quan hóa Histogram theo phân nhóm sử dụng FacetGrid
g = sns.FacetGrid(df, col="phanlopt1", col_order=['k', 'tb', 'kh', 'g'], height=4, aspect=1)
g.map(sns.histplot, "T1", kde=True, color='crimson')
g.set_titles("Nhóm: {col_name}")
plt.show()


# =====================================================================
# CÂU 3: KHẢO SÁT TƯƠNG QUAN GIỮA BIẾN DH1 THEO BIẾN T1
# =====================================================================
print("\n===== CÂU 3 =====")

# Nhận xét giá trị Covariance (Hiệp phương sai) và Correlation (Hệ số tương quan)
covariance_t1_dh1 = df['T1'].cov(df['DH1'])
correlation_t1_dh1 = df['T1'].corr(df['DH1'])

print(f"Hiệp phương sai (Covariance) giữa T1 và DH1: {covariance_t1_dh1:.4f}")
print(f"Hệ số tương quan Pearson (Correlation) giữa T1 và DH1: {correlation_t1_dh1:.4f}")
if correlation_t1_dh1 > 0:
    print("-> Nhận xét: T1 và DH1 có tương quan tuyến tính thuận (đồng biến).")
elif correlation_t1_dh1 < 0:
    print("-> Nhận xét: T1 và DH1 có tương quan tuyến tính nghịch (nghịch biến).")
else:
    print("-> Nhận xét: Không có tương quan tuyến tính giữa T1 và DH1.")

# Vẽ biểu đồ Scatter thể hiện mối liên hệ (DH1 là biến phụ thuộc -> Trục Y, T1 là biến độc lập -> Trục X)
plt.figure(figsize=(7, 5))
sns.scatterplot(x='T1', y='DH1', data=df, color='#c0504d', s=50, edgecolor='black')
# Thêm đường xu hướng tuyến tính (Trendline) để dễ quan sát mối quan hệ
sns.regplot(x='T1', y='DH1', data=df, scatter=False, color='black', label='Đường xu hướng')
plt.title('Biểu đồ Scatter biểu diễn mối quan hệ giữa DH1 theo T1')
plt.xlabel('Biến độc lập T1')
plt.ylabel('Biến phụ thuộc DH1')
plt.grid(True, linestyle='--', alpha=0.6)
plt.show()


# =====================================================================
# CÂU 4: KHẢO SÁT TƯƠNG QUAN GIỮA DH1 THEO T1 TRÊN TỪNG NHÓM KHU VỰC
# =====================================================================
print("\n===== CÂU 4 =====")

# Lưu ý: Do trong tập mẫu hiện tại chưa có biến khu vực (KV), ta sẽ giả lập cột 'KV'
# để code chạy được trọn vẹn yêu cầu câu 4. (Nếu dùng file thật của bạn, hãy xóa dòng giả lập dưới đây).
if 'KV' not in df.columns:
    df['KV'] = np.random.choice(['KV1', 'KV2', 'KV3'], size=len(df))

# Tính toán hệ số tương quan theo từng nhóm khu vực
for name, group in df.groupby('KV'):
    corr_val = group['T1'].corr(group['DH1'])
    print(f"Hệ số tương quan giữa T1 và DH1 tại nhóm khu vực {name}: {corr_val:.4f}")

# Vẽ biểu đồ Scatter phân tách màu sắc hoặc phân ô theo từng khu vực
plt.figure(figsize=(8, 5))
sns.scatterplot(x='T1', y='DH1', hue='KV', data=df, palette='Dark2', s=60)
plt.title('Biểu đồ Scatter giữa DH1 theo T1 phân loại theo Khu vực')
plt.xlabel('Điểm T1')
plt.ylabel('Điểm DH1')
plt.grid(True)
plt.show()


# =====================================================================
# CÂU 5: KHẢO SÁT TƯƠNG QUAN GIỮA CÁC BIẾN DH1, DH2, DH3
# =====================================================================
print("\n===== CÂU 5 =====")

# Lập ma trận hiệp phương sai (Covariance Matrix)
ma_tran_hiep_phuong_sai = df[['DH1', 'DH2', 'DH3']].cov()
print("--- Ma trận hiệp phương sai (Covariance Matrix) ---")
print(ma_tran_hiep_phuong_sai)

# Lập ma trận tương quan (Correlation Matrix)
ma_tran_tuong_quan = df[['DH1', 'DH2', 'DH3']].corr()
print("\n--- Ma trận tương quan (Correlation Matrix) ---")
print(ma_tran_tuong_quan)

# Trực quan hóa ma trận tương quan bằng biểu đồ nhiệt Heatmap
plt.figure(figsize=(6, 5))
sns.heatmap(ma_tran_tuong_quan, annot=True, cmap='Blues', fmt=".4f", linewidths=0.5)
plt.title('Biểu đồ Heatmap ma trận tương quan giữa DH1, DH2, DH3')
plt.show()

# Vẽ biểu đồ Scatter giữa các cặp biến bằng PairPlot
print("\nĐang khởi tạo biểu đồ đa hướng Scatter giữa các cặp biến...")
sns.pairplot(df[['DH1', 'DH2', 'DH3']], diag_kind='kde', plot_kws={'color':'#8064a2'})
plt.suptitle('Biểu đồ Scatter Matrix giữa các biến DH1, DH2, DH3', y=1.02)
plt.show()